# Generated by Django 5.2.1 on 2025-05-26 22:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_time', models.TimeField(default=datetime.time(9, 0))),
                ('duration', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Chờ Xác Nhận'), ('confirmed', 'Đã Xác Nhận'), ('cancelled', 'Đã Hủy'), ('completed', 'Hoàn Thành'), ('missed', 'Lỡ Hẹn')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Bình Thường'), ('urgent', 'Khẩn Cấp'), ('emergency', 'Cấp Cứu')], default='normal', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Lý do khám')),
                ('symptoms', models.TextField(blank=True, help_text='Triệu chứng')),
                ('note', models.TextField(blank=True, help_text='Ghi chú thêm')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
                'unique_together': {('doctor_id', 'appointment_date', 'appointment_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointment.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
