# Generated by Django 5.2.1 on 2025-05-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_appointment_date'),
    ]

    operations = [
    ]
