# Generated by Django 5.2.1 on 2025-05-27 04:50

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_add_missing_fields'),  # hoặc migration cuối cùng của bạn
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.RunSQL(
            "ALTER TABLE appointment_appointment DROP COLUMN IF EXISTS scheduled_time;"
        ),
    ]
