# Generated by Django 5.2.1 on 2025-05-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_rename_notes_appointment_note_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE appointment_appointment DROP COLUMN IF EXISTS scheduled_time;"
        ),
    ]
