# Generated by Django 5.2.1 on 2025-05-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('medications', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='phamacry.medication')),
            ],
        ),
    ]
