# Generated by Django 5.2.1 on 2025-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
